// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7lI5pmWd7iPBgtjDCy7rd7MvyrPPSt3A',
    appId: '1:68254204410:web:ae3be26ed72926387f2443',
    messagingSenderId: '68254204410',
    projectId: 'ecrunchies',
    authDomain: 'ecrunchies.firebaseapp.com',
    storageBucket: 'ecrunchies.appspot.com',
    measurementId: 'G-YYHY7HE4BQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEPlNfSWOey7SKew_W4BEpSxSZawFJ3-w',
    appId: '1:68254204410:android:726fa554da9c42d67f2443',
    messagingSenderId: '68254204410',
    projectId: 'ecrunchies',
    storageBucket: 'ecrunchies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMgBSZhdvGY9LK5HSGmNIyCVzT3N3LAYk',
    appId: '1:68254204410:ios:8506f087985f37117f2443',
    messagingSenderId: '68254204410',
    projectId: 'ecrunchies',
    storageBucket: 'ecrunchies.appspot.com',
    iosBundleId: 'com.example.ecrunchies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMgBSZhdvGY9LK5HSGmNIyCVzT3N3LAYk',
    appId: '1:68254204410:ios:95ce5149ecd3ae8e7f2443',
    messagingSenderId: '68254204410',
    projectId: 'ecrunchies',
    storageBucket: 'ecrunchies.appspot.com',
    iosBundleId: 'com.example.ecrunchies.RunnerTests',
  );
}
